### ISSUE TITLE
Read your news article..

### ISSUE THREAD

**Issue by ghost** [makeuseofcode/CAPTCHA-Validator#1]
Hey,

I love the idea of providing info on how to make your own captcha, but honestly this attempt does nothing to prevent spam.

-  no server side validation for your captcha, meaning bots can/will just bypass the captcha all together
- any spam bot will be configured to pick up simple captcha data from an element (at least try canvas the text?)

Fighting spam bots is not a trivial task, and so more consideration should be taken before offering advice like this.

**Comment by kwsim539** [comment]
> Hey,
> 
> I love the idea of providing info on how to make your own captcha, but honestly this attempt does nothing to prevent spam.
> 
> * no server side validation for your captcha, meaning bots can/will just bypass the captcha all together
> * any spam bot will be configured to pick up simple captcha data from an element (at least try canvas the text?)
> 
> Fighting spam bots is not a trivial task, and so more consideration should be taken before offering advice like this.

I agree that this will not stop the spammers and I think using canvas for the text is a good idea. Trying to minimize requests on a site is a big deal nowadays and if this would be retrofitted with the text canvas, I would be willing to give it a try.

**Comment by Yuvrajchandra** [comment]
Hey @DigitalEnki @kwsim539 
Thanks a lot for your suggestion guys. I'll fix that!
Using canvas for the text is a great idea. 
Thanks again!

**Comment by Yuvrajchandra** [comment]
Fixed it!
